### ISSUE TITLE
knife-block not working

### ISSUE THREAD

**Issue by allaire** [knife-block/knife-block#14]
I get this following error when I try to run knife-block, I'm using master version of knife-block, here's the trace:

```
.chef|⇒ knife block list -VV
/Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/knife-block-dc563985b564/lib/chef/knife/block.rb:18:in `get_config_file': undefined method `locate_config_file' for Chef::Knife:Class (NoMethodError)
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/knife-block-dc563985b564/lib/chef/knife/block.rb:37:in `chef_config_base'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/knife-block-dc563985b564/lib/chef/knife/block.rb:74:in `check_block_setup'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bundler/gems/knife-block-dc563985b564/lib/chef/knife/block.rb:141:in `run'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chef-11.6.2/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chef-11.6.2/lib/chef/knife.rb:173:in `run'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chef-11.6.2/lib/chef/application/knife.rb:123:in `run'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chef-11.6.2/bin/knife:25:in `<top (required)>'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/bin/knife:23:in `load'
	from /Users/allaire/.rbenv/versions/2.0.0-p247/bin/knife:23:in `<main>'
```

**Comment by levmichael3** [comment]
I got this issue as well, after removing the gems directory (cleaning them all) and installing the gem again.
I got the same thing, "Exception: NoMethodError: undefined method `locate_config_file' for Chef::Knife:Class"
Ill fork the fix from the PR of woohgit :)
Ill try to fork the fix from the PR of

**Comment by levmichael3** [comment]
poop!
Still no luck...
[******@*** ***]$ gem list | grep block
knife-block (0.0.9)
[********@*** ****]$ knife block list
ERROR: knife encountered an unexpected error
This may be a bug in the 'block list' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `locate_config_file' for #<Chef::Knife:0x00000003ae7010>

**Comment by woohgit** [comment]
This is because it has been already changed in the never versions, so you should locate the problem and fix it again :)

**Comment by solarce** [comment]
Tracking in https://github.com/knife-block/knife-block/issues/25
