### ISSUE TITLE
Undefined method "locate_config_file" with chef 12 / chefdk 0.3.5

### ISSUE THREAD

**Issue by cheaprbytheduzn** [knife-block/knife-block#25]
Upon upgrading from chefdk 0.2.0 to 0.3.5, knife block broke down emitting:

Exception: NoMethodError: undefined method `locate_config_file' for Chef::Knife:Class

The 0.3.5 version of:
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-11.6.2/lib/chef/knife.rb

does indeed have changes to locate_config_file from the comparable 0.2.0 which no doubt has implicatations for knife-block's own get_config_file / locate_config_file logic.  

There were a few intervening releases from 0.2.0 to 0.3.5 that I did not use.

Chefdk 0.3.5 has no problems with the knife-block gem removed and knife-block works fine when installed with 0.2.0.

To workaround the problem, I donwgraded to 0.2.0 for now.

**Comment by clintoncwolfe** [comment]
#26 is a proposed fix for this

**Comment by tbunnyman** [comment]
This is also broken in chefdk 0.4.0 which is not too surprising.

**Comment by ikurochkin** [comment]
+1

**Comment by solarce** [comment]
We should have this fixed up soon, got a couple PRs to get merged, but we're close!

**Comment by solarce** [comment]
Fixes for this got merged in https://github.com/knife-block/knife-block/pull/37.
