### ISSUE TITLE
knife block v0.2.0 does NOT show available servers

### ISSUE THREAD

**Issue by cfoutsgit** [knife-block/knife-block#44]
knife-block v0.2.0
chef-client v12.1.1
chef-server v12.0.0

I have a knife-server1.rb in my ~/.chef dir, and a ~/.knife.rb symlink to it

$ ls -al .chef
-rw-rw-r--  1 builder builder  841 Mar 19 11:54 knife-server1.rb
lrwxrwxrwx  1 builder builder   22 Mar 19 12:06 knife.rb -> knife-server1.rb

$ knife block list
The available chef servers are:

The output shows nothing.

**Comment by solarce** [comment]
My apologies, I discovered this yesterday and got better testing and a fix done but didn't have time to push a new gem until now.

I've pushed [v0.2.1](https://github.com/knife-block/knife-block/releases/tag/v0.2.1) to [Rubygems](https://rubygems.org/gems/knife-block/versions/0.2.1) and am gonna pull v0.2.0 and update my [blog post](http://www.solarce.org/writing/knife-block-v0.2.0/) shortly.

@cfoutsgit, If you have time, please grab the gem and test it out, some extra confirmation would be great

**Comment by solarce** [comment]
Fix in https://github.com/knife-block/knife-block/pull/43 resolves this.

**Comment by cfoutsgit** [comment]
knife-block v0.2.1

$ knife block list
The available chef servers are:
        * altonbrowndev [ Currently Selected ]
        * altonbrownqa
