### ISSUE TITLE
knife-block needs a new owner

### ISSUE THREAD

**Issue by mrjcleaver** [knife-block/knife-block#46]
In https://github.com/knife-block/knife-block/issues/20 proffalken commented on Apr 16, 2014

> I am no longer using Knife Block at work and I do not have time to maintain it in my spare time owing to my personal life.

New owner needed (new ticket to alert watchers)

**Comment by solarce** [comment]
@mrjcleaver I am the new owner of knife-block, is there a particular issue that you need help in getting addressed? I recently got out a [0.2.1]https://github.com/knife-block/knife-block/releases/tag/v0.2.1) which had fixes for chef12 and chefdk.

As I have time I am going to try and get the code through rubocop and get OSX/Windows CI going.

**Comment by mrjcleaver** [comment]
Oh, am sorry, I only looked at #20 - I didn't realize anyone had taken over. Great!

I thought I'd posted another issue. I'll see if I can find it or will repost. Thanks. M.
