### ISSUE TITLE
`get_config_file': undefined method `locate_config_file' for Chef

### ISSUE THREAD

**Issue by okram999** [knife-block/knife-block#50]
This issue which is supposedly closed is coming back on me for some repos/workspace. 

I am using - knife-block (0.1.1)

Below is the verbose log:

±  |master ✓| → knife block -VV
INFO: Using configuration from /home/user/.chef/knife.rb
/home/user/.rvm/gems/ruby-2.1.1@ASK/gems/knife-block-0.1.1/lib/chef/knife/block.rb:16:in `get_config_file': undefined method `locate_config_file' for Chef::Knife:Class (NoMethodError)
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/knife-block-0.1.1/lib/chef/knife/block.rb:38:in `chef_config_base'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/knife-block-0.1.1/lib/chef/knife/block.rb:75:in `check_block_setup'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/knife-block-0.1.1/lib/chef/knife/block.rb:101:in `run'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/lib/chef/knife.rb:213:in `run'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/lib/chef/application/knife.rb:139:in `run'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/gems/chef-12.0.3/bin/knife:25:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/bin/knife:23:in `load'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/bin/knife:23:in `<main>'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/bin/ruby_executable_hooks:15:in `eval'
	from /home/user/.rvm/gems/ruby-2.1.1@ASK/bin/ruby_executable_hooks:15:in `<main>'

I have cloned these repo's just yesterday, on to an old workstation. This workstation have the chefDK 0.3.5 installed. I am not sure if this make any difference, but the cookbooks/repo that i cloned were written on a different workstation where i have the chefDK 0.6.0

the knife files are placed under the ~/.chef/ dir

**Comment by okram999** [comment]
Not surprised, the chefDK update to 0.6.0 makes no change to the issue

**Comment by nshemonsky** [comment]
The issue was related to a change with chef-client 12+ that was fixed with the release of knife-block 0.2.0.  See: https://github.com/knife-block/knife-block/pull/37

I would recommend updating to the latest release of the gem, 0.2.1.

**Comment by okram999** [comment]
@nshemonsky :+1: hey, that did the trick. thanks!
