### ISSUE TITLE
Show current knife in use in shell prompt

### ISSUE THREAD

**Issue by benvaljean** [knife-block/knife-block#51]
Are there any plans to show the current knife configuration in use in the shell prompt? If not I can consider writing it, if you would like to pull it. Or would you consider such functionality better handled in a separate project/repo?

Thanks,

Benjamin

**Comment by solarce** [comment]
I'd happily accept a PR. Since i'm not really using chef with a server at Travis this project is kinda just on maintenance right now. I've been meaning to see about finding 1-2 people who'd want to help with possible future development

**Comment by benvaljean** [comment]
#52 PR created

**Comment by solarce** [comment]
@benvaljean I am no longer using knife-block and don't really have the time to steward it anymore :( Would you be interested in working on it? I'd be happy to get you access to GH and rubygems if so

**Comment by benvaljean** [comment]
Ok great. Ruby is not one of my primary languages though. Outside of chef I have not done much on it.

**Comment by solarce** [comment]
@benvaljean is that a yes? :) if so would you email me your rubygems account name and email, to solarce@gmail.com? Thanks!

**Comment by benvaljean** [comment]
@solarce Yes it is a yes :)  I emailed you my details, thanks!

**Comment by benvaljean** [comment]
https://github.com/knife-block/knife-block/pull/54 was merged and addresses this issue
