### ISSUE TITLE
Update advertised Ruby version in gemspec

### ISSUE THREAD

**Issue by mcandre** [knife-block/knife-block#56]
The README says knife-block requires Ruby 1.9.2+, while the RubyGems page says any version would work.

https://rubygems.org/gems/knife-block

Please update the gemspec to resolve this ambiguity. See https://github.com/mcandre/lili/blob/master/lili.gemspec#L19 for an example

**Comment by benvaljean** [comment]
@mcandre Looks good?

**Comment by mcandre** [comment]
+1
